### ISSUE TITLE
Replication issues upon first deployment

### ISSUE THREAD

**Issue by KittyKatt** [pando85/kaniop#68]
Hello again! After getting past my last issue, I started seeing issues once the pods were up attempting to contact and reconcile with each other:
```
DEBUG    ┝━ proxy_read [ 26.0µs | 1.29% / 1.42% ]
DEBUG    │  ┕━ read_acquire_ticket [ 2.40µs | 0.13% ]
DEBUG    ┝━ supplier_provide_changes [ 4.76µs | 0.26% ]
ERROR    │  ┝━ 🚨 [error]: Replication - Consumer Domain UUID does not match our local domain uuid.
DEBUG    │  ┕━ 🐛 [debug]:  | consumer_domain_uuid: fd088c24-8704-408c-bb68-30e8e58d5287 | supplier_domain_uuid: d3eb4d5a-efd2-49f8-b5e9-7c4815435973
DEBUG    ┕━ 🐛 [debug]: replication client disconnected 🛬 | client_address: 10.244.9.200:43532
INFO     repl_run_consumer [ 54.1ms | 0.59% / 100.00% ] domain: "ic_refresh: false | consumer_conn_settings: ConsumerConnSettings { max_frame_bytes: 268435456, task_poll_interval: 15s, replica_connect_timeout: 2s } | eventid: "707a9082-f06b-48e6-af35-513efc492a2f"
INFO     ┝━ repl_consumer_connect_supplier [ 1.10ms | 2.02% ]
DEBUG    │  ┕━ 🐛 [debug]: Attempting to connect to DEBUG    ┝━ proxy_read [ 17.2µs | 0.03% / 0.03% ]
DEBUG    │  ┕━ read_acquire_ticket [ 1.49µs | 0.00% ]
DEBUG    ┝━ consumer_get_state [ 2.04µs | 0.00% ]
DEBUG    ┝━ proxy_write [ 27.7ms | 51.19% / 51.20% ]
DEBUG    │  ┕━ write_acquire_ticket [ 3.08µs | 0.01% ]
ERROR    ┝━ 🚨 [error]: Unable to proceed with consumer incremental - the supplier has indicated that our domain_uuid's are not equivalent. This can occur when adding a new consumer to an existing topology.
ERROR    ┝━ 🚨 [error]: This server's content must be refreshed to proceed. If you have configured automatic refresh, this will occur shortly.
DEBUG    ┝━ commit [ 25.0ms | 0.03% / 46.16% ]
INFO     │  ┕━ qswt_commit [ 25.0ms | 0.77% / 46.13% ]
DEBUG    │     ┕━ idl_arc_sqlite::commit [ 24.5ms | 0.06% / 45.36% ]
DEBUG    │        ┕━ idl_sqlite::commit [ 24.5ms | 45.30% ]
ERROR    ┕━ 🚨 [error]: Consumer is out of date and must be refreshed. You must manually resolve this situation.
INFO     handle_repl_conn [ 2.32ms | 97.75% / 100.00% ]
DEBUG    ┝━ 🐛 [debug]: replication client connected 🛫 | client_address: 10.244.9.200:34962
DEBUG    ┝━ proxy_read [ 46.3µs | 1.81% / 2.00% ]
DEBUG    │  ┕━ read_acquire_ticket [ 4.35µs | 0.19% ]
DEBUG    ┝━ supplier_provide_changes [ 5.94µs | 0.26% ]
ERROR    │  ┝━ 🚨 [error]: Replication - Consumer Domain UUID does not match our local domain uuid.
INFO     repl_run_consumer [ 37.4ms | 1.01% / 100.00% ] domain: "tic_refresh: false | consumer_conn_settings: ConsumerConnSettings { max_frame_bytes: 268435456, task_poll_interval: 15s, replica_connect_timeout: 2s } | eventid: "087043c5-53a2-470f-8130-179eb021820b"
INFO     ┝━ repl_consumer_connect_supplier [ 1.64ms | 4.39% ]
DEBUG    │  ┕━ 🐛 [debug]: Attempting to connect to DEBUG    ┝━ proxy_read [ 51.9µs | 0.13% / 0.14% ]
DEBUG    │  ┕━ 🐛 [debug]:  | consumer_domain_uuid: fd088c24-8704-408c-bb68-30e8e58d5287 | supplier_domain_uuid: c97b9e89-80c8-48b8-94c7-7b4f8b095c42
DEBUG    │  ┕━ read_acquire_ticket [ 3.21µs | 0.01% ]
DEBUG    ┝━ consumer_get_state [ 6.30µs | 0.02% ]
DEBUG    ┝━ proxy_write [ 14.9ms | 39.78% / 39.78% ]
DEBUG    │  ┕━ write_acquire_ticket [ 2.19µs | 0.01% ]
ERROR    ┝━ 🚨 [error]: Unable to proceed with consumer incremental - the supplier has indicated that our domain_uuid's are not equivalent. This can occur when adding a new consumer to an existing topology.
ERROR    ┝━ 🚨 [error]: This server's content must be refreshed to proceed. If you have configured automatic refresh, this will occur shortly.
DEBUG    ┝━ commit [ 20.4ms | 0.04% / 54.66% ]
INFO     │  ┕━ qswt_commit [ 20.4ms | 0.22% / 54.62% ]
DEBUG    │     ┕━ idl_arc_sqlite::commit [ 20.3ms | 0.08% / 54.40% ]
DEBUG    │        ┕━ idl_sqlite::commit [ 20.3ms | 54.32% ]
ERROR    ┕━ 🚨 [error]: Consumer is out of date and must be refreshed. You must manually resolve this situation.
```

I went to go look for `domain_uuid` in Kanidm's documentation and [found this](https://kanidm.github.io/kanidm/stable/repl/deployment.html):
> Then restart both servers. Initially the servers will refuse to synchronise as their databases do not have matching domain_uuids. To resolve this you can instruct B to manually refresh from A with:
> 
> \# Server B
> docker exec -i -t <container name> \
>   kanidmd refresh-replication-consumer

So I decided to try executing this on all pods and got the following error:
```
╰─ >>> k exec -n kaniop beep-boop-primary-2 -- kanidmd refresh-replication-consumer
📜 Using config file: "/data/server.toml"
Logging pipeline completed shutdown
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: This is running as uid == 0 (root) which may be a security risk.
00000000-0000-0000-0000-000000000000 WARN     🚧 [warn]: WARNING: DB folder /data has 'everyone' permission bits in the mode. This could be a security risk ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Running refresh replication consumer ...
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unwilling to proceed. Check --help.
```

 Despite turning on trace logging level in Kanidm, I couldn't seem to get any more logs out of it than that. However, looking through `--help`, I found this option:
```
      --i-want-to-refresh-this-servers-database
          Acknowledge that this database content will be refreshed from a supplier
```

And since this isn't my production domain, I figured "why not" and tried it. It succeeded on all three nodes and they are no longer spitting out tons of error lines every few seconds. Unsure if this is a known issue? Let me know if I can do any more testing, I'm totally willing to tear this down and get back into error state again.

For reference, I am attempting to create a three pod single replication group.
```
  replicaGroups:
    - name: primary
      replicas: 3
```

**Comment by pando85** [comment]
Hello again @KittyKatt .

That's normal, it is the desired state for a Kanidm cluster. I implemented an option for allowing to have a primary node which will act as the reference for synchronization. 

With the lack of documentation I just can point you to the code (you could check the CRD too): https://github.com/pando85/kaniop/blob/master/libs%2Fkanidm%2Fsrc%2Fcrd.rs#L252

Those keys are camel case in the Kubernetes object. So with

**Comment by KittyKatt** [comment]
Oh, THAT'S what that does. Okay, this all makes sense. I did actually find that but I'm not familiar enough with Rust to really read it accurately and tell what it does. Thanks, I'll give this a try.

**Comment by pando85** [comment]
Ahh, ok. Probably there you can contribute. The important part in Rust there is that the keys are going to be transformed to the case needed. In this case is camelCase, but there those keys are defined by me in a more or less opinionated way. 

In concrete, that key was defined by me because in Kanidm you have [this auto refresh value](https://kanidm.github.io/kanidm/stable/repl/deployment.html#partially-automated-node-configurations) and it's the way that I think that it make sense to use it. Just for defining one node that take the lead. 

It can be defined in just one replication group or one external node. Probably documentation there (the `///` comments) has to be improved. 
Let me know your opinion/understanding of that. Obviously with some specific docs with examples this will be improved.
